---
baseurl: "/"
url: ''
title: Dizer -  Multipurpose Business & Corporate Jekyll Template
email: estaennosotraspiloto@gmail.com
phone: 2539-2222
address: Costa Rica, San José, Zapote, 400 metros oeste de Casa Presidencial Edificio
  Mira, primer piso
author: themefisher
description: Dizer - Multipurpose Business & Corporate Jekyll Template Jekyll Theme
  For Mobile Apps Download Landing Page And Blogging.
logo: "/assets/images/logo.png"
logo_icon: "/assets/images/logo-b.png"
contact_form_action: "#"
mailchimp_list: https://themeix.us16.list-manage.com/subscribe/post?u=307862c135e4548eecf86f389&amp;id=342411fb35
footer_content: Este sitio brinda información sobre las carreras STEM para chicas
  que deseen incursionar en estas áreas.
copyright: dizer. &copy; 2020 All Right Reserved
cover_image: "/assets/images/bg/about-bg.jpg"
google_map_api: https://maps.googleapis.com/maps/api/js?key=AIzaSyDnh74UN6BKgq9U5fMNGhdZOSpmM_QnZqs
cta:
  enable: true
  title: dizer give the smart solution for your business
  bg_image: "/assets/images/bg/cta-bg-2.png"
  button:
    label: get a quote
    link: contact
social:
- name: ''
  icon: ''
  link: ''
- name: facebook
  icon: ti-facebook
  link: "#"
permalink: "/:title"
markdown: kramdown
plugins:
- jekyll-feed
- jekyll-paginate-v2
- jekyll-archives
sass:
  sass_dir: assets/scss
  style: compressed
collections:
  portfolios:
    output: true
pagination:
  enabled: true
  debug: false
  collection: posts
  per_page: "6"
  permalink: "/blog/:num/"
  title: ":title - page :num"
  limit: "0"
  sort_field: date
  sort_reverse: true
  category: posts
  tag: ''
  locale: ''
  trail:
    before: "2"
    after: "2"
  extension: html
  indexpage: index
tag_page_layout: tag_page
tag_page_dir: tag
tag_permalink_style: pretty
jekyll-archives:
  enabled: all
  layout: category
  permalinks:
    category: "/category/:name/"
feed:
  collections:
    posts:
      path: "/index.xml"
